/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FooterLoginView: typeof import('./src/components/FooterLoginView.vue')['default']
    FooterView: typeof import('./src/components/FooterView.vue')['default']
    HeaderLoginView: typeof import('./src/components/HeaderLoginView.vue')['default']
    HeaderView: typeof import('./src/components/HeaderView.vue')['default']
    IconExample: typeof import('./src/components/icons/IconExample.vue')['default']
    LogoExample: typeof import('./src/components/icons/LogoExample.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusAtivo: typeof import('./src/components/icons/StatusAtivo.vue')['default']
  }
}
