/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DropZoneView: typeof import('./src/components/dropzone/DropZoneView.vue')['default']
    FooterView: typeof import('./src/components/FooterView.vue')['default']
    HeaderView: typeof import('./src/components/HeaderView.vue')['default']
    IconExample: typeof import('./src/components/icons/IconExample.vue')['default']
    LoginFooter: typeof import('./src/components/footer/LoginFooter.vue')['default']
    LoginHeader: typeof import('./src/components/header/LoginHeader.vue')['default']
    LogoExample: typeof import('./src/components/icons/LogoExample.vue')['default']
    MainFooter: typeof import('./src/components/footer/MainFooter.vue')['default']
    MainHeader: typeof import('./src/components/header/MainHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusAtivo: typeof import('./src/components/icons/StatusAtivo.vue')['default']
  }
}
